"""Added calorie goals to User model

Revision ID: 7c833d31c4e4
Revises: 
Create Date: 2024-09-27 22:42:41.154043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c833d31c4e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_intake', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goal_burn', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('goal_burn')
        batch_op.drop_column('goal_intake')

    # ### end Alembic commands ###
